// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYG7hAUfogodXKEOzkbaNGcfWn7Scl-xM',
    appId: '1:445891553108:web:3cc70da137be18cb164ac1',
    messagingSenderId: '445891553108',
    projectId: 'ecommerce-86981',
    authDomain: 'ecommerce-86981.firebaseapp.com',
    storageBucket: 'ecommerce-86981.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeTbi7XEYD_BsW8LPS5ozD9ykk4FX_m4',
    appId: '1:445891553108:android:2d37b68edc21762d164ac1',
    messagingSenderId: '445891553108',
    projectId: 'ecommerce-86981',
    storageBucket: 'ecommerce-86981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCl79KCUGQjiirxTxVlhweEfsjEZ3QiwM',
    appId: '1:445891553108:ios:c439f6899f595af8164ac1',
    messagingSenderId: '445891553108',
    projectId: 'ecommerce-86981',
    storageBucket: 'ecommerce-86981.appspot.com',
    androidClientId: '445891553108-25f8tdvh4ld88j7hfhtk14uph797i7km.apps.googleusercontent.com',
    iosClientId: '445891553108-70rktd3qsucuvokid1lthai32ub0p9r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCl79KCUGQjiirxTxVlhweEfsjEZ3QiwM',
    appId: '1:445891553108:ios:c439f6899f595af8164ac1',
    messagingSenderId: '445891553108',
    projectId: 'ecommerce-86981',
    storageBucket: 'ecommerce-86981.appspot.com',
    androidClientId: '445891553108-25f8tdvh4ld88j7hfhtk14uph797i7km.apps.googleusercontent.com',
    iosClientId: '445891553108-70rktd3qsucuvokid1lthai32ub0p9r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYG7hAUfogodXKEOzkbaNGcfWn7Scl-xM',
    appId: '1:445891553108:web:23f909524ce26b27164ac1',
    messagingSenderId: '445891553108',
    projectId: 'ecommerce-86981',
    authDomain: 'ecommerce-86981.firebaseapp.com',
    storageBucket: 'ecommerce-86981.appspot.com',
  );
}
